# Generated by Django 2.2 on 2020-08-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0003_auto_20200819_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='codigo',
        ),
    ]
