# Generated by Django 2.2 on 2020-08-19 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0005_auto_20200819_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='alumno',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblio.Alumno'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblio.Libro'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='profesor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblio.Profesor'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='revista',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblio.Revista'),
        ),
    ]
