# Generated by Django 2.2 on 2020-08-19 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0006_auto_20200819_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='revista',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='material',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblio.Material'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='persona',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblio.Persona'),
        ),
    ]
