# Generated by Django 2.2 on 2020-08-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0009_tipopersona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipopersona',
            old_name='Alumno',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='tipopersona',
            old_name='Profesor',
            new_name='profesor',
        ),
    ]
