# Generated by Django 2.2 on 2020-08-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0010_auto_20200819_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='portada',
            field=models.ImageField(blank=True, upload_to='fotosPortada/'),
        ),
    ]
